server:
  port: 7000
logging:
  level:
    org.hibernate.stat: DEBUG

db:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://localhost:8066/diplom_taxi
  username: default
  password: default

spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
  config:
    import: redis-config.yaml

jwt:
  secret: bbbb12312312345346ggggggg12312312345346rrrrr12312312345346qqq
  lifetime:
    seconds: 86400