spring:
  jpa:
    properties:
      cache:
        redisson:
          defaultCache:
            expiration:
              max_entities: 1000
              time_to_live: 259200000
          query:
            eviction:
              max_entries: 500
              expiration:
                time_to_live: 14400000